### ISSUE TITLE
MAX5026EUT+T replacement

### ISSUE THREAD

**Issue by dr4kan** [OpenGammaProject/Mini-SiD#12]
Hi,

first of all thank you for making available this project. I am interested in buying one assembled pcb to play with, so I tried to use jlcpcb.com. However, it looks like the MAX5026EUT+T is unavailable not only there, but also on lcsc.com. How can it be replaced without changing the design of the pcb?

Thanks

**Comment by NuclearPhoenixx** [comment]
Hi,

just use another distributor. Let JLCPCB assemble everything but the MAX5026 and then just order and solder that part for yourself.
You can get it pretty easily elsewhere, e.g. on mouser or digikey:
- https://www.mouser.at/ProductDetail/Analog-Devices-Maxim-Integrated/MAX5026EUT%2bT?qs=Mqkh4jHMT8zfiFUMsw6rrA%3D%3D
- https://www.digikey.at/de/products/detail/analog-devices-inc-maxim-integrated/MAX5026EUT-T/1516355?s=N4IgTCBcDaILIEEAaBWADGAbAUQKoBUBqfAAhAF0BfIA

I've even seen the MAX5026 sold on ebay at reasonable prices, so it really shouldn't be hard to get one :)

Hope that helps!
